apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: gotraining
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: gotraining
    tier: frontend
